"""empty message

Revision ID: 246ff1d13b9d
Revises: 
Create Date: 2024-07-23 14:04:08.604902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246ff1d13b9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('park_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=80), nullable=False),
    sa.Column('event', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('park_data')
    # ### end Alembic commands ###
